dhakaworker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.pages.urls')),
]


urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image

# Create your models here.
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils.text import slugify


class WorkerCategory(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = " Category (admin work)"

@receiver(pre_save,sender=WorkerCategory)
def pre_save_category_slug(sender,instance,**kwargs):
    instance.slug=slugify(instance.name)


class WorkingArea(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField()
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = " Area (admin work)"

@receiver(pre_save,sender=WorkingArea)
def pre_save_area_slug(sender,instance,**kwargs):
    instance.slug=slugify(instance.name)


# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         return super(PublishedManager, self).get_queryset().filter(status=True)
#
# class AllObjectManager(models.Manager):
#     def get_queryset(self):
#         return super(AllObjectManager, self).get_queryset()

class WorkerProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='worker_profile')
    fullname = models.CharField(max_length=40,null=True,blank=True)
    category = models.ForeignKey(WorkerCategory,on_delete=models.CASCADE,null=True,blank=True)
    working_time = models.CharField(max_length=100,null=True,blank=True)
    hourly_rate  = models.FloatField(null=True,blank=True)
    working_area = models.ManyToManyField(WorkingArea)
    extra_service = models.CharField(max_length=250,null=True,blank=True)
    experience = models.FloatField(null=True,blank=True)
    phone      = models.IntegerField(null=True,blank=True)
    views      = models.PositiveIntegerField(default=0, blank=True)
    image      = models.ImageField(upload_to='profile_pic/',blank=False,null=False,default="default.jpg")

    created    = models.DateTimeField(auto_now_add=True)

    status = models.BooleanField(default=False)

    # published = PublishedManager()
    # objects   = AllObjectManager()


    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['-views']


        verbose_name_plural = "Worker Profiles"


@receiver(pre_save, sender=WorkerProfile)
def check_status_of_profile(instance, *args, **kwargs):
    if (instance.fullname is not None and instance.category is not None and instance.working_time is not None
        and instance.hourly_rate is not None and instance.phone is not None):
        instance.status = True
    else:
        instance.status = False

class Message(models.Model):
    worker = models.ForeignKey(WorkerProfile,on_delete=models.CASCADE,related_name='worker_message')
    name  = models.CharField(max_length=100,blank=False,null=False)
    email = models.EmailField(blank=True,null=True)
    phone = models.IntegerField()
    message=models.TextField(blank=False,null=False)
    time =models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering= ['-time']
        verbose_name_plural="Messages"


# when user create also create a profile
@receiver(post_save,sender=User)
def post_create_profile(instance,created,*args,**kwargs):
    if created:
        WorkerProfile.objects.get_or_create(user=instance)

apps/pages/templates/filterview.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">

						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/MAID-SERVANT.png' %}" style="height:270px;width:250px;margin-bottom:20px;"alt="#" />
						</div><!--/shipping-->

						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/SECURITY-GUARD.png' %}"style="height:270px;width:250px;margin-bottom:20px;" alt="" />
						</div><!--/shipping-->



						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/ELECTRICIAN.png' %}" style="height:270px;width:250px;margin-bottom:20px; "alt="" />
						</div><!--/shipping-->

						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/DRIVER.png' %}"style="height:270px;width:250px;margin-bottom:20px;" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						{% with request.resolver_match.url_name as url_name %}
						{% if url_name == "search_view" %}
								<h2 class="title text-center">Result For "{{ request.GET.search }}"</h2>
						{% endif %}

						<h2 class="title text-center">{{ request.resolver_match.kwargs.slug }}</h2>
						{% endwith %}

                        {% for object in object_list %}
						<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{ object.image.url }}" alt="" />
													<h2>{{object.fullname}}</h2>
													<p>{{ object.category.name}}</p>
													<p>{% for area in object.working_area.all %} {{ area }} {% endfor %}</p>
													<a href="{% url 'worker_detail' pk=object.pk %}" class="btn btn-default add-to-cart">View Details </a>
												</div>

											</div>
										</div>
									</div>
								{% empty %}
								<p class="text-center"> NO WORKER FOUND !</p>
                        {% endfor %}


<!--						<ul class="pagination">-->
<!--							<li class="active"><a href="">1</a></li>-->
<!--							<li><a href="">2</a></li>-->
<!--							<li><a href="">3</a></li>-->
<!--							<li><a href="">&raquo;</a></li>-->
<!--						</ul>-->
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>
{% endblock body %}

apps/pages/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block body %}



	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>DhakaWorker</span>.Com</h1>
									<h2>Top Class Elecrician</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Know More</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/slide1 (2).jpg' %}" class="girl img-responsive" alt="" />

								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>DhakaWorker</span>.Com</h1>
									<h2>Trusted Home Maid</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Know More</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/slide2.jpg' %}" class="girl img-responsive" alt="" />

								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<h1><span>DhakaWorker</span>.Com</h1>
									<h2>Top Rated Driver</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Know More</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/slide3.jpg' %}" class="girl img-responsive" alt="" />

								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">

									<h1><span>DhakaWorker</span>.Com</h1>
									<h2>Top Security Guard</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Know More</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/slide4.jpg' %}" class="girl img-responsive" alt="" />

								</div>
							</div>
						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->

	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Area</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for area in area_list %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a href="{% url 'area_filter' slug=area.name %}" >

											{{ area.name }}
										</a>
									</h4>
								</div>
							</div>
					 		{% endfor %}

						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Number Of Registared Workers </h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
<!--									<li><a href="#"> <span class="pull-right">(50)</span>Maid Servant </a></li>-->
									{% for category in category_list%}
									<li><a href="{% url 'category_filter' slug=category.slug %}"> <span class="pull-right">({{category.workerprofile_set.all.count}})</span>{{category.name}}</a></li>

									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->



						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/ELECTRICIAN.png' %}" style="height:270px;width:250px;margin-bottom:20px; "alt="" />
						</div><!--/shipping-->
						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/DRIVER.png' %}"style="height:270px;width:250px;margin-bottom:20px;" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 col-mb-9 col-lg-9 padding-right">
					<div class="features_items"><!--Top Worker-->
						<h2 class="title text-center">Top Worker</h2>
				<div class="row">
			 {% for object in object_list %}
					<div class="col-sm-4 col-mb-4 col-lg-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="{{object.image.url}}" alt="" />
											 <h2>{{object.fullname}}</h2>
											<p>{{object.category.name}}</p>
											{% for area in object.working_area.all %}
											<a href="#" class=" btn btn-sm add-to-cart"></i>{{area.name}}</a>
											{% endfor %}
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>{{object.hourly_rate}} TK / Hour</h2>
												<p> {{object.views}} times profile view</p>
												<a href="{% url 'worker_detail' pk=object.pk %}" class="btn btn-default add-to-cart"></i>See Details</a>
											</div>
										</div>
								</div>

							</div>
						</div>
			{% endfor %}
					</div>

					</div><!--Top Worker End-->



				</div>
			</div>
		</div>
	</section>

{% endblock body %}

apps/pages/templates/message_modal.html
<!-- Central Modal Small -->
<div class="modal fade" id="message_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <!-- Change class .modal-sm to change the size of the modal -->
  <div class="modal-dialog modal-lg modal-notify modal-warning" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title w-100" id="myModalLabel"> Send Message For Hire</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="col-12 grid-margin">

                  <form class="form-sample" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                  <div class="row text-center ">
                      <div class="col-md-12">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Name</label>
                          <div class="col-sm-9">
                           {{ form.name.error}}
                           {{ form.name}}
                          </div>
                        </div>
                      </div>
                     <div class="col-md-12">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Phone</label>
                          <div class="col-sm-9">
                           {{ form.phone.error }}
                           {{ form.phone }}
                          </div>
                        </div>
                      </div>


                      <div class="col-md-12">
                        <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Email </label>
                          <div class="col-sm-9">
                            {{ form.email.error }}
                            {{ form.email }}
                          </div>
                        </div>
                      </div>



                      <div class="col-md-12">
                        <div class="form-group row">

                          <label class="col-sm-3 col-form-label">Message</label>
                          <div class="col-sm-9">
                              {{ form.message.error }}
                            {{ form.message }}
                          </div>
                        </div>
                      </div>
                  </div>


            </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>


        <button type="submit" class="btn btn-success btn-icon-text">
                          <i class="mdi mdi-file-check btn-icon-prepend"></i>
                          Send
                        </button>
      </div>

                  </form>

    </div>
  </div>
</div>
</div>
<!-- Central Modal Small -->

apps/pages/templates/messages.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Dashboard</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a  href="#sportswear">
											<div class="dashimg">
                                                Profile Views : {{object.worker_profile.views}} times
											</div>
										</a>
									</h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:bold;border:1px solid green;hob">
									<h4 class="panel-title"style="margin-left:70px;">
										<a  href="{% url 'profile_view' request.user.username %}">
											Profile Details
										</a>
									</h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:italic;border:1px solid green;">
									<h4 class="panel-title"style="margin-left:80px;"><a href="{% url 'messages' request.user.username %}">Messages</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:italic;border:1px solid green;">
									<h4 class="panel-title"style="margin-left:80px;"><a href="{% url 'logout' %}">Logout</a></h4>
								</div>
							</div>
						</div><!--/category-products-->
					</div>
				</div>

<!--                {% for object in object_list %}-->
<!--                <p>{{object.name}}</p>-->
<!--                {% endfor %}-->
<div class="col-md-9">
<p class="lead text-center"> Messages From Interested Client</p>
	<hr>
				<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Client Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col">Message</th>
      <th scope="col">Time</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
  {% for object in object_list %}
    <tr>
      <th scope="row">{{object.name}}</th>
      <td>{{object.phone}}</td>
      <td>{{object.email}}</td>
      <td>{{object.message}}</td>
      <td>{{object.time}}</td>
      <td ><button  type="button" class="btn btn-danger" onclick="myFunction() ">Delete</button></td>
    </tr>

<!--  delete confirm dialogue-->
  <script>
function myFunction() {
  var txt;
  if (confirm("Do you want to delete!")) {
   window.location.href = "{% url 'message_delete' pk=object.pk %}";
  } else {
  //don't do anything
  }

}
</script>
  {% endfor %}

  </tbody>
</table>
</div>
			</div>
		</div>
	</section>




{% endblock body %}

apps/pages/templates/profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Dashboard</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a  href="#sportswear">
											<div class="dashimg">
                                                Profile Views : {{object.worker_profile.views}} times
											</div>
										</a>
									</h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:bold;border:1px solid green;hob">
									<h4 class="panel-title"style="margin-left:70px;">
										<a  href="{% url 'profile_view' object.username%}">
											Profile Details
										</a>
									</h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:italic;border:1px solid green;">
									<h4 class="panel-title"style="margin-left:80px;"><a href="{% url 'messages' request.user.username %}">Messages</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:italic;border:1px solid green;">
									<h4 class="panel-title"style="margin-left:80px;"><a href="{% url 'logout' %}">Logout</a></h4>
								</div>
							</div>
						</div><!--/category-products-->
					</div>
				</div>

				<div class="col-sm-9 padding-right">

                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

						 {% for field in form %}
							<div class="fieldWrapper">
								{{ field.errors }}
								{{ field.label_tag }} {{ field }}
							</div>
						{% endfor %}



						<button  style="margin-bottom:10%;margin-top:1%;" type="submit" class="btn btn-default">Save</button>
                    </form>


				</div>
			</div>
		</div>
	</section>

{% endblock body %}

apps/pages/templates/worker_detail.html
{% extends 'base.html' %}

{% load static %}

{% block body %}



	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<div class="shipping text-center"><!--shipping-->

							<img src="{% static 'images/home/DRIVER.png' %}"style="height:270px;width:250px;margin-bottom:20px;" alt="" />
						</div><!--/shipping-->

						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/ELECTRICIAN.png' %}" style="height:270px;width:250px;margin-bottom:20px; "alt="" />
						</div><!--/shipping-->





					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="{{object.image.url}}"style="height:200px;width:200px;margin-left:50px;margin-top:70px;" alt="" />

							</div>
							<div id="similar-product" class="carousel slide" data-ride="carousel">




							</div>

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->

								 <h2>{{object.fullname}}</h2>
								<p>{{object.category.name}} / {% for area in object.working_area.all %} {{area.name}}, {% endfor %}</p>

								<p>{{object.views}} times view</p>
								<div class="price">
								<h2>{{ object.hourly_rate}} TK / Hour</h2>
								</div>
								<p><b>Working Availability:</b> {{ object.working_time }} </p>
								<p><b>Extra Service:</b> {{object.extra_service}} </p>
								<p><b>Experience:</b> {{ object.experience }} years</p>

								<button type="button" class="btn btn-fefault cart"  data-toggle="modal" data-target="#message_modal">

										Click For Hire
									</button>


							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->



					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended Worker</h2>

						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								{% for worker in recommend_worker %}
								<div class="item active">
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{ worker.image.url }}" alt="" />
													<h2>{{worker.fullname}}</h2>
													<p>{{worker.category.name}}</p>
													<p>{% for area in worker.working_area.all %} {{area.name}}, {% endfor %}</p>
													<a href="{% url 'worker_detail' worker.id %}" class="btn btn-default add-to-cart">View Details </a>
												</div>

											</div>
										</div>
									</div>

								</div>
								{% empty %}
								<p class="text-center"> NO RECOMMEND WORKER</p>
								{% endfor %}

							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>
						</div>
					</div><!--/recommended_items-->

				</div>
			</div>
		</div>
	</section>





{% include 'message_modal.html' %}

{% endblock body %}

apps/pages/templates/worker_profile.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Dashboard</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">

											<div class="dashimg">
                                                Profile Views : {{object.worker_profile.views}} times
											</div>
										</a>
									</h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:bold;border:1px solid green;hob">
									<h4 class="panel-title"style="margin-left:70px;">
										<a  href="{% url 'profile_view' object.username%}">
											Profile Details
										</a>
									</h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:italic;border:1px solid green;">
									<h4 class="panel-title"style="margin-left:80px;"><a href="{% url 'messages' request.user.username %}">Messages</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading"style="font-style:italic;border:1px solid green;">
									<h4 class="panel-title"style="margin-left:80px;"><a href="{% url 'logout' %}">Logout</a></h4>
								</div>
							</div>
						</div><!--/category-products-->
					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--Top Worker-->
					<div class="profile-details" style="margin-bottom:20px;">

					<img src="{{object.worker_profile.image.url}}"style="height:100px;width:100px;border-radius:50%;margin-left:380px;"/>
					<h3 style="text-align:center;">{{ object.worker_profile.fullname }}</h3>
                        <p class="text-center">Username : <strong>{{request.user.username}}</strong></p>
                        <p class="text-center">Email : <strong>{{object.email}}</strong></p>
                        <p class="text-center">Contact No : <strong>{{object.worker_profile.phone}}</strong></p>
					<p style="margin-left:43%;border:1px solid gold;width:15%;text-align:center;background-color:gray;color:white;">{{object.worker_profile.category.name}}</p>
					 <h3>#<a  href="{% url 'profile_edit_view' request.user.username %}" class="text-center"> <strong>Edit </strong></a></h3>

					<h4 style="margin-left:20px;margin-top:20px;">My work Responsibilities:</h4>
					<p style="margin-left:20px;margin-top:20px;"> {{ object.worker_profile.extra_service}}</p>
					<h4 style="margin-left:20px;margin-top:20px;">Working Time:</h4>
					<p style="margin-left:20px;margin-top:10px;">{{ object.worker_profile.working_time}}</p>
					<h4 style="margin-left:20px;margin-top:20px;">Working Area:</h4>
					<p style="margin-left:20px;margin-top:10px;">{% for area in object.worker_profile.working_area.all %}{{area.name}}|{% endfor %}</p>
 					<h4 style="margin-left:20px;margin-top:20px;display:inline;">My Hourly Rate:</h4>
					<p style="margin-left:20px;margin-top:20px;display:inline;"> {{ object.worker_profile.hourly_rate}} Taka</p>


                    </div>
					</div><!--Top Worker End-->






				</div>
			</div>
		</div>
	</section>

{% endblock body %}